{{- if .Values.snapshotConfig.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  labels:
    created-by: {{ template "elasticsearch.name" . }} 
    name: {{ template "elasticsearch.name" . }}-snapshots
  name: {{ template "elasticsearch.name" . }}-snapshots
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: edcop-nfs
  resources:
    requests:
      storage: {{ .Values.snapshotConfig.pvc.storage }}
{{- end -}}
